Switch to a newer fork of capsule
Running the latest docker image produces the error message "CAPSULE
EXCEPTION: Could not parse version: 11.0.9.1 while processing
attribute Min-Update-Version: {} (for stack trace, run with
-Dcapsule.log=verbose)".  Replace our old capsule dependency with
io.nextflow's fork to fix the problem.